### ISSUE TITLE
Doesn't load with Manual Install for Windows Atom 1.0.19

### ISSUE THREAD

**Issue by bauchter-work** [rhoconlinux/language-do#1]
For many various reasons, I'm tied to windows for most work.  I've placed the package into the .atom/packages folder, but I get the following error when loading Atom 1.0.19 in Windows (7):

```
Unexpected token < in C:\Users\<MY_USER>\.atom\packages\language-do-master\package.json
Hide Stack Trace
SyntaxError: Unexpected token <
    at Object.parse (native)
    at parseObject (C:\Temp\Atom\resources\app.asar\node_modules\season\lib\cson.js:54:19)
    at parseContentsSync (C:\Temp\Atom\resources\app.asar\node_modules\season\lib\cson.js:68:16)
    at Object.module.exports.readFileSync (C:\Temp\Atom\resources\app.asar\node_modules\season\lib\cson.js:170:14)
    at Function.module.exports.Package.loadMetadata (C:\Temp\Atom\resources\app.asar\src\package.js:69:29)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Temp\Atom\resources\app.asar\src\package-manager.js:388:39)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Temp\Atom\resources\app.asar\src\package-manager.js:369:14)
    at Atom.module.exports.Atom.startEditorWindow (C:\Temp\Atom\resources\app.asar\src\atom.js:667:21)
    at Object.<anonymous> (C:\Temp\Atom\resources\app.asar\src\window-bootstrap.js:12:8)
    at Object.<anonymous> (C:\Temp\Atom\resources\app.asar\src\window-bootstrap.js:23:4)
  at C:\Users\<MY_USER>\.atom\packages\language-do-master\package.json:1:1
```

Any ideas??

Thanks!

**Comment by pbly** [comment]
It seems that the file loading blocks because of the >>>>> and <<< inserted in the code. I'm not super familiar with Git but I think those come from a merge conflict that wasn't resolved properly.

**Comment by rhoconlinux** [comment]
weard man... try directly from the app? 
Sorry but have no clue of what is happening...
